import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Service from '../src/modules/services/models/Service.js';

dotenv.config();

const webDevServices = [
    {
        name: 'Startup Website',
        slug: 'startup-website',
        type: 'web-development',
        category: 'Web Development',
        description: 'Perfect for startups, freelancers, local businesses, and personal brands. Launch your business online with a clean, responsive, and professional website.',
        fullDescription: 'Launch your business online with a clean, responsive, and professional website designed to create trust and generate leads. We build modern, fast-loading websites that make a strong first impression and help you stand out from the competition.',
        icon: 'rocket',
        price: 4999,
        pricingLabel: 'Starting at ₹4,999',
        status: 'active',
        order: 1,
        recommended: false,
        badge: 'Best for Startups',
        features: [
            { name: 'Modern responsive website design', value: 'Included', included: true },
            { name: 'Mobile-friendly UI', value: 'Included', included: true },
            { name: 'Fast-loading optimized pages', value: 'Included', included: true },
            { name: 'Contact forms and inquiry system', value: 'Included', included: true },
            { name: 'Social media integration', value: 'Included', included: true },
            { name: 'Basic SEO setup', value: 'Included', included: true },
            { name: 'Google Maps integration', value: 'Included', included: true },
            { name: 'SSL setup support', value: 'Included', included: true },
            { name: 'Basic speed optimization', value: 'Included', included: true },
            { name: '1 month support', value: 'Included', included: true },
        ],
        deliverables: [
            'Responsive website',
            'Contact form',
            'Social media links',
            'Google Maps embed',
            'Basic SEO setup',
        ],
        techStack: ['React.js', 'Next.js', 'Tailwind CSS', 'Node.js'],
    },
    {
        name: 'Business Growth Website',
        slug: 'business-growth-website',
        type: 'web-development',
        category: 'Web Development',
        description: 'Designed for businesses that want more leads, authority, and conversions. Professional branding and lead generation focused.',
        fullDescription: 'Our business websites are focused on professional branding, lead generation, customer engagement, and long-term business growth. We build websites that not only look great but also work as powerful marketing tools to grow your business.',
        icon: 'trending-up',
        price: 7999,
        pricingLabel: 'Starting at ₹7,999',
        status: 'active',
        order: 2,
        recommended: true,
        badge: 'Most Popular',
        features: [
            { name: 'Custom business website design', value: 'Included', included: true },
            { name: 'Professional UI/UX structure', value: 'Included', included: true },
            { name: 'Lead generation forms', value: 'Included', included: true },
            { name: 'Service pages and content sections', value: 'Included', included: true },
            { name: 'SEO optimized architecture', value: 'Included', included: true },
            { name: 'Analytics integration', value: 'Included', included: true },
            { name: 'WhatsApp integration', value: 'Included', included: true },
            { name: 'CRM integration support', value: 'Included', included: true },
            { name: 'Speed optimization', value: 'Included', included: true },
            { name: 'Mobile and tablet optimization', value: 'Included', included: true },
            { name: 'Security setup', value: 'Included', included: true },
            { name: 'Performance monitoring', value: 'Included', included: true },
        ],
        deliverables: [
            'Custom business website',
            'Lead gen forms',
            'WhatsApp chat integration',
            'SEO architecture',
            'Analytics setup',
        ],
        techStack: ['React.js', 'Next.js', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    },
    {
        name: 'E-Commerce Store',
        slug: 'ecommerce-store',
        type: 'web-development',
        category: 'Web Development',
        description: 'Sell products online with a complete ecommerce ecosystem. Modern UI, payment integration, and optimized shopping experiences.',
        fullDescription: 'We develop scalable ecommerce stores with modern UI, payment integration, inventory systems, and optimized shopping experiences. From small boutiques to large multi-vendor platforms, we build stores that drive sales.',
        icon: 'shopping-cart',
        price: 11999,
        pricingLabel: 'Starting at ₹11,999',
        status: 'active',
        order: 3,
        recommended: false,
        badge: '',
        features: [
            { name: 'Ecommerce website development', value: 'Included', included: true },
            { name: 'Product management system', value: 'Included', included: true },
            { name: 'Shopping cart functionality', value: 'Included', included: true },
            { name: 'Payment gateway integration', value: 'Included', included: true },
            { name: 'Order management dashboard', value: 'Included', included: true },
            { name: 'Inventory management', value: 'Included', included: true },
            { name: 'Coupon & discount system', value: 'Included', included: true },
            { name: 'Product SEO optimization', value: 'Included', included: true },
            { name: 'Responsive design', value: 'Included', included: true },
            { name: 'User account system', value: 'Included', included: true },
            { name: 'Admin dashboard', value: 'Included', included: true },
            { name: 'Analytics setup', value: 'Included', included: true },
        ],
        deliverables: [
            'Full ecommerce store',
            'Payment integration',
            'Order management',
            'Product catalog',
            'Admin dashboard',
        ],
        techStack: ['React.js', 'Next.js', 'Node.js', 'MongoDB', 'Stripe/Razorpay'],
    },
    {
        name: 'Custom Web Application',
        slug: 'custom-web-application',
        type: 'web-development',
        category: 'Web Development',
        description: 'Powerful custom-built applications tailored for your business. Scalable, secure, and production-grade.',
        fullDescription: 'We develop scalable and secure web applications using modern technologies and production-grade architecture. From SaaS platforms to internal business tools, we build applications that drive real business value.',
        icon: 'layout',
        price: 34999,
        pricingLabel: 'Starting at ₹34,999',
        status: 'active',
        order: 4,
        recommended: false,
        badge: 'Popular',
        features: [
            { name: 'Custom frontend and backend development', value: 'Included', included: true },
            { name: 'API development and integration', value: 'Included', included: true },
            { name: 'Authentication systems', value: 'Included', included: true },
            { name: 'Role-based access control', value: 'Included', included: true },
            { name: 'Admin dashboards', value: 'Included', included: true },
            { name: 'Database architecture', value: 'Included', included: true },
            { name: 'Real-time features', value: 'Included', included: true },
            { name: 'Security implementation', value: 'Included', included: true },
            { name: 'Scalable deployment', value: 'Included', included: true },
            { name: 'Performance optimization', value: 'Included', included: true },
            { name: 'Maintenance support', value: 'Included', included: true },
        ],
        deliverables: [
            'Full-stack application',
            'API documentation',
            'Admin dashboard',
            'Auth system',
            'Deployment setup',
        ],
        techStack: ['MERN Stack', 'Next.js', 'PostgreSQL', 'Redis', 'Docker'],
    },
    {
        name: 'Managed Hosting Solutions',
        slug: 'managed-hosting-solutions',
        type: 'web-development',
        category: 'Web Development',
        description: 'Fast, secure, and reliable hosting infrastructure with managed support and performance optimization.',
        fullDescription: 'We provide managed hosting solutions with performance optimization, security monitoring, backups, and 24/7 technical assistance. Your website or application runs on optimized infrastructure with expert support.',
        icon: 'server',
        price: 399,
        pricingLabel: 'Starting at ₹399/month',
        status: 'active',
        order: 5,
        recommended: false,
        badge: '',
        features: [
            { name: 'Server setup and configuration', value: 'Included', included: true },
            { name: 'SSL installation', value: 'Included', included: true },
            { name: 'Daily backups', value: 'Included', included: true },
            { name: 'Security hardening', value: 'Included', included: true },
            { name: 'Firewall setup', value: 'Included', included: true },
            { name: 'Monitoring and uptime tracking', value: 'Included', included: true },
            { name: 'Technical support', value: 'Included', included: true },
            { name: 'Email hosting support', value: 'Included', included: true },
            { name: 'Performance optimization', value: 'Included', included: true },
            { name: 'CDN support', value: 'Included', included: true },
        ],
        deliverables: [
            'Managed server setup',
            'SSL certificate',
            'Backup system',
            'Monitoring dashboard',
            'Support access',
        ],
        techStack: ['Docker', 'AWS', 'Cloudflare', 'NGINX', 'Linux'],
    },
    {
        name: 'SEO & Digital Growth',
        slug: 'seo-digital-growth',
        type: 'web-development',
        category: 'Web Development',
        description: 'Improve visibility, traffic, and business growth with comprehensive SEO and digital marketing services.',
        fullDescription: 'Our SEO and growth services help businesses improve search engine rankings, attract quality traffic, and increase conversions. We use data-driven strategies to deliver measurable results.',
        icon: 'search',
        price: 1999,
        pricingLabel: 'Starting at ₹1,999/month',
        status: 'active',
        order: 6,
        recommended: false,
        badge: '',
        features: [
            { name: 'Keyword research', value: 'Included', included: true },
            { name: 'On-page SEO', value: 'Included', included: true },
            { name: 'Technical SEO audit', value: 'Included', included: true },
            { name: 'SEO content optimization', value: 'Included', included: true },
            { name: 'Website performance optimization', value: 'Included', included: true },
            { name: 'Google indexing optimization', value: 'Included', included: true },
            { name: 'Search Console setup', value: 'Included', included: true },
            { name: 'Analytics setup', value: 'Included', included: true },
            { name: 'Monthly reports', value: 'Included', included: true },
            { name: 'Competitor analysis', value: 'Included', included: true },
            { name: 'Growth consultation', value: 'Included', included: true },
        ],
        deliverables: [
            'SEO audit report',
            'Keyword strategy',
            'Content optimization',
            'Analytics dashboard',
            'Monthly performance report',
        ],
        techStack: ['Google Analytics', 'Search Console', 'SEMrush', 'Ahrefs'],
    },
    {
        name: 'Enterprise SaaS & Portal',
        slug: 'enterprise-saas-portal',
        type: 'web-development',
        category: 'Web Development',
        description: 'Enterprise-grade systems built for scalability and performance. Large-scale platforms with secure infrastructure.',
        fullDescription: 'We develop large-scale SaaS platforms, enterprise portals, and business systems with secure infrastructure and scalable architecture. Built for organizations that need robust, high-performance digital solutions.',
        icon: 'building',
        price: 69999,
        pricingLabel: 'Starting at ₹69,999',
        status: 'active',
        order: 7,
        recommended: false,
        badge: 'Enterprise',
        features: [
            { name: 'Enterprise architecture planning', value: 'Included', included: true },
            { name: 'Multi-user system development', value: 'Included', included: true },
            { name: 'Team management system', value: 'Included', included: true },
            { name: 'Analytics and reporting dashboards', value: 'Included', included: true },
            { name: 'Advanced security implementation', value: 'Included', included: true },
            { name: 'API integrations', value: 'Included', included: true },
            { name: 'Cloud infrastructure setup', value: 'Included', included: true },
            { name: 'High scalability support', value: 'Included', included: true },
            { name: 'Database optimization', value: 'Included', included: true },
            { name: 'DevOps support', value: 'Included', included: true },
            { name: 'Long-term maintenance', value: 'Included', included: true },
        ],
        deliverables: [
            'Full enterprise platform',
            'Multi-tenant architecture',
            'Admin dashboards',
            'API integrations',
            'Cloud deployment',
        ],
        techStack: ['Next.js', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    },
    {
        name: 'Dedicated Developer Team',
        slug: 'dedicated-developer-team',
        type: 'web-development',
        category: 'Web Development',
        description: 'Hire dedicated developers for your long-term projects. Skilled professionals working directly on your project.',
        fullDescription: 'Expand your business with skilled developers working directly on your project with transparent workflows and ongoing collaboration. Scale your team up or down based on your project needs.',
        icon: 'users',
        price: 17999,
        pricingLabel: 'Starting at ₹17,999/month per developer',
        status: 'active',
        order: 8,
        recommended: false,
        badge: '',
        features: [
            { name: 'Dedicated resource allocation', value: 'Included', included: true },
            { name: 'Agile development workflow', value: 'Included', included: true },
            { name: 'Weekly updates and reporting', value: 'Included', included: true },
            { name: 'Bug fixing and maintenance', value: 'Included', included: true },
            { name: 'Feature implementation', value: 'Included', included: true },
            { name: 'Direct communication support', value: 'Included', included: true },
            { name: 'Task tracking and management', value: 'Included', included: true },
            { name: 'Flexible scaling', value: 'Included', included: true },
        ],
        deliverables: [
            'Dedicated developer(s)',
            'Weekly reports',
            'Code repository access',
            'Task board',
            'Communication channel',
        ],
        techStack: ['React.js', 'Node.js', 'MongoDB', 'PostgreSQL', 'Docker'],
    },
];

async function seedServices() {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');
        console.log('Seeding WebGenix Services...\n');

        for (const data of webDevServices) {
            const existing = await Service.findOne({ slug: data.slug });
            if (existing) {
                console.log(`  Updating: ${data.name}`);
                Object.assign(existing, data);
                await existing.save();
            } else {
                console.log(`  Creating: ${data.name}`);
                await Service.create(data);
            }
        }

        const count = await Service.countDocuments();
        console.log(`\n Total services seeded: ${count}`);
    } catch (error) {
        console.error('Error seeding services:', error);
    } finally {
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    }
}

seedServices();
